#!/usr/bin/env bash
#
#  Synopsis:
#	Libexecs script to merge multiple tar files into a single tar file.
#  Description:
#	Merge the files from several different *.dist files into a single
#	tar file suitable for deployment.  The merged tar file can be unpacked
#	in the root target directory.
#
#	The cool symbol ꛷ for a question comes from the Banum people of
#	west africa.
#  Usage:
#	cd ~/src/github.com/jmscott/setspace
#	git pull
#
#	DIST1=setspace.dist
#	DIST2=schema/setcore/setspace-schema-setcore.dist
#	DIST3=schema/pdfbox/setspace-schema-pdfbox.dist
#	TAG=setspace-$(git rev-parse --short HEAD)
#	
#	make-dist tars $TAG $DIST1 $DIST2 $DIST3		|| exit 1
#	TAR=$(echo $TAG-[0-9]*.tar.bz)
#	cp $TAR ~/opt/setspace/dist/
#	cd ~/opt/setspace
#	#  stop processes for setcore and pdfbox
#	tar xvf dist/$TAR
#	#  start processes for setcore and pdfbox
#  Requires:
#	gnu realpath find bash tar date
#	jmscott elapsed-english
#	
#  Exit Status:
#	0	tars merged into single tar <tag>-YYYYMMDD_hhmm.tar.bz2
#	1	failure
#  Note:
#	Consider moving the individual tar files into the respective dirs/dist.
#
#	Extract the name of the individual tar file from the new var
#	$TAR_FILE_BASE in the *.dist file.
#

PROG=make-dist-tars
START_EPOCH=$(date +%s)
TAG=
WORK_TMP=
START_DIR=$(pwd)
TAR_BZ2_REGEX='-[123][0-9]{7}_[0-5][0-9]{3}[.]tar[.]bz2$'

#  map dist base to realpath of containing directory
declare -A tarbz2dir_path

WARN()
{
	PREAMBLE=$PROG
	test -n "$TAG" && PREAMBLE="$PREAMBLE-$TAG"
	echo "$PREAMBLE: WARN: $@" >&2
}

zap_work_tmp()
{
	test -n "$WORK_DIR" -a -d $WORK_DIR || return
	cd "$START_DIR"
	"-$WORK_TMP"
	rm -rf $WORK_TMP || WARN "rm tmp/work/ failed: exit status=$?"
	WORK_TMP=
}

leave()
{
	zap_work_tmp
	echo "#  $PROG: good bye, cruel world: $(elapsed-english $START_EPOCH)"
}

die()
{
	PREAMBLE="$PROG"
	test -n "$TAG" && PREAMBLE="$PREAMBLE-$TAG"
	echo "$PREAMBLE: ERROR: $@" >&2
	exit 1
}

#
#  rm stale tar files built with "make-dist tar"
#
#  Note:
#	what about escaping regex metachars in $DIST?
#
find_dist_tar()
{
	DIST_PATH="$1"
	DIST=$(basename "$DIST_PATH" .dist)
	DIST_DIR=$(dirname "$DIST_PATH")

	find "$DIST_DIR"						\
		-maxdepth 1						\
		-type f							\
		-regextype posix-extended				\
		-regex '.*/'"$DIST$TAR_BZ2_REGEX"
}

#  remove stale tar.bz2 files of previous dist pulls.

purge_tar()
{
	find_dist_tar $1						|
	  while read TAR;  do
	  	echo "-$TAR"
		rm -f $TAR || die "rm old tar.bz failed: exit status=$?"
	  done
}

make_dist_tar()
{
	local DIST=$1

	cd "$START_DIR" || die "cd start dir failed: exit status=$?"

	DIST_DIR=$(dirname $DIST)
	echo "->$DIST_DIR"
	DIST_DIR=$(realpath $DIST_DIR --relative-to "$START_DIR")
	cd $DIST_DIR || die "cd dist dir failed: exit status=$?"
	BASE_DIST=$(basename $DIST)
	echo "<$BASE_DIST"
	make-dist tar $BASE_DIST || die "make-dist failed: exit status=$?"

	for TAR in $(find_dist_tar $BASE_DIST);  do
		mv $TAR $WORK_TMP/dist				||
			die "mv tar to tmp/work/dist failed: exit status=#?"

		local _TAR
		_TAR=$(basename $TAR)
		#  Note: need to verify no duplicates!
		tarbz2dir_path["$_TAR"]=$DIST_DIR
	done
}

unpack_dist_tar()
{
	local TAR_NAME
	local TAR_PATH
	local DIST_PATH

	cd $WORK_TMP || die "cd work/tmp start unpack failed: exit status=$?"
	TAR_PATH=$1
	TAR_NAME=$(basename $TAR_PATH)
	echo "꛷$TAR_PATH"

	DIST_PATH="${tarbz2dir_path[$TAR_NAME]}"
	test -n "$DIST_PATH" || die "can not find dist path: $TAR_NAME"
	echo "+>$DIST_PATH"
	mkdir -p $DIST_PATH || die "mkdir unpack dist failed: exit status=$?"

	TAR_PATH=$(realpath --relative-to $DIST_PATH $TAR_PATH)
	cd $DIST_PATH || die "cd unpack dist path failed: exit status=$?"
	tar xvf $TAR_PATH || die "tar x unpack failed: exit status=$?"
}

#  verify paths to dist files

trap leave EXIT
echo
echo "#  $PROG: hello, world"

TAG="$1";  shift

#  verify the dist files exist

for DIST in $*;  do
	case $DIST in
	*' '*)
		die "space not allowed in dist path: $DIST"
		;;
	*.dist)
		echo "✓$DIST"
		test -r $DIST || die "can not read dist file: $DIST"
		purge_tar $DIST || exit
		;;
	*)
		die "dist file must has .dist suffix: $DIST"
		;;
	esac
done

#  assemble the temp work dir in which to unpack the indvidually built tar.bz2
#  files.
WORK_TMP=${TMPDIR:=/tmp}/$PROG-$$.d
echo "+>$WORK_TMP/dist"
mkdir -p $WORK_TMP/dist || die "mkdir -p tmp/work/dist failed: exit status=$?"

WORK_TMP=$(realpath $WORK_TMP)

#  build a tar file for each dist file by executing "make dist" in the
#  containing directory.

for DIST in $*;  do
	make_dist_tar $DIST || exit
done

echo "->$WORK_TMP"
cd $WORK_TMP || die "cd work tmp failed: exit status=$?"

for TAR in dist/*.tar.bz2;  do
	unpack_dist_tar $TAR || exit
done

cd $WORK_TMP || die "cd work/tmp post unpack failed: exit status=$?"

#  bundle the temp directory into single tar in $START_DIR

tar cvf $START_DIR/$TAG-$(date +'%Y%m%d_%H%M').tar.bz2 . --bzip2	||
	die "tar tmp/work failed: exit status=$?"

exit 0
