#!/bin/bash
#
#  Synopsis:
#	Chatty, conditional exec of a cron job monitored by file run/<proc>.pid
#  Usage:
#	cron-run-once <stale-seconds> path/to/exec arg1 arg2 ...
#  Exit Code:
#	0	process execed with exit status of 0
#	<64	exit status of execed cron job
#	64	fresh process running
#	126	unexpcedt error
#	127	une
#  See:
#	$JMSCOTT_ROOT/bin/zap-proc
#
