#!/bin/bash
#
#  Synopsis:
#	Is a file or standard input well formed json?
#  Usage:
#	isjson <x.json
#	isjson x.json
#  Exit Status:
#	0	input is well formed json
#	1	input is not well formed json
#	2	unknown error
#  Note:
#	Extend to more than one file!
#

die()
{
	echo "ERROR: $@" >&2
	exit 2
}

# valid path to eexecutable
is_exec()
{
	EXE=$1
	which $EXE >/dev/null 2>&1
	STATUS=$?
	test $STATUS -le 1 && return $STATUS
	die "which $EXE failed: exit status=$STATUS"
}

case $# in
0)
	;;
1)
	#  sadly, file existence exit with status 1
	test -r $1 || die "can not read file: $1"
	;;
*)
	die "wrong number of arguments: got $#, expected < 2"
	;;
esac

#  Find executable "python", which is python2.
#  otherwise, use python3, if exists.
#  the pain never ends.

PYTHON=python
if is_exec $PYTHON;  then
	true
else
	PYTHON=python3
	if is_exec $PYTHON;  then
		true
	else
		die 'cannot find python exec'
	fi
fi

$PYTHON -m json.tool $1 >/dev/null 2>&1
STATUS=$?
case $STATUS in
0)
	ANSWER="YES: valid"
	;;
1)
	ANSWER="NO: invalid"
	;;
127)
	die "exit status=127: is python installed?"
	;;
*)
	die "python json failed: exit status=$STATUS"
	;;
esac

if [ $# = 0 ];  then
	echo "$ANSWER json"
else
	echo "$ANSWER json: $1"
fi
exit $STATUS
