#!/bin/sh
#
#  Synopsis:
#	Script to bundle a files set into {bin,lib,htdocs,cgi-bin} tar file
#  Description:
#	This script 'make-dist' creates a tar of a "distribution" to be unpacked
#	in a typical SystemV filesystem layout:
#
#		$ROOT/bin
#		$ROOT/sbin
#		$ROOT/lib
#		$ROOT/etc
#		$ROOT/spool
#		$ROOT/log
#		$ROOT/run
#		$ROOT/src
#
#	Additional are web directories to support http access: cgi-bin, htdocs
#
#		$ROOT/run
#		$ROOT/src
#
#  Usage:
#	make-dist --help
#	make-dist --template >setspace.conf
#	vi setspace.con
#
#	make-dist setspace.conf
#	D=$(pwd)
#	cd /path/to/product/root && tar xvf $D/setspace-20140403_1213.tar
#  GitHub:
#	https://github.com/jmscott/work/blob/master/make-dist
#

PROG=$(basename $0)
USAGE="$PROG [--help] [--template] <configuration-file>"

help()
{
	cat <<END

Synopsis:
	Build a tar archive file suitable for unpacking into a product tree.
Usage:
	$USAGE
Description:
	$PROG reads a configuration file and builds a bzipped tar file of the 
	files in a typical unix directory layout.  The confiugration files
	contains bourne shell variable definitions.  The tar file is 
	suitable for unpacking to install or upgrade a target host.  
	The files rebuilt in the tar archive into the following sub directories:
	
		./	#  Base level files/directorys.
		bin/	#  read only executables executed by cli or scripts
		sbin/	#  read only executables executed by daemons/services.
		src/	#  compilable source code, not scripts.
		lib/	#  read only support files.  typically sql scripts,
			#    perl libraries, etc.
	    cgi-bin/	#  cgi-scripts for web server
	     htdocs/	#  htdoc scripts for web server
		
	In the configuration file are environment variables BINs, CGIBINs, 
	LIBs, CGIBINs, SBINs and HTDOCs that contain the source file list for
	each target directory.

	The compressed tar file is written into a file named 

		$PRODUCT-YYYYMMDD_HHmm.tar.bz2.

	where PRODUCT is the $(basename $(pwd)).  To change the basename of
	the product, define the PRODUCT environment variable in the
	configuration file.

		PRODUCT=setspace

	To unpack the tar file on the production host, do something like

		scp \$PRODUCT-YYMMDD_HHMM.tar.bz2 \$PRODUCT@host:/tmp
		ssh \$PRODUCT@host
		cd <target-dir>
		bzcat /tmp/\$PRODUCT-YYMMDD_HHMM.tar.bz2 | tar xvf -
Depends:
	tar, a popular gnu archiver, gnu xargs, and bzip2.
	Needs write permission in current directory.
Exit Status:
	0	no error
	1	error, temp build directory, named ./tmp/make-dist.\$\$,
			left intact.
Note:
	Need to use mtree format for directory layout.
END
}

PRODUCT=$(basename $(pwd))

die()
{
	echo "$PROG: ERROR: $@" >&2
	echo "usage: $USAGE"
	exit 1
}

is_readable()
{
	VAR=$1
	CMD='FILES=$(echo $'$VAR')'
	eval $CMD
	for F in $FILES;  do
		test -r $F || die "$VAR: can't read file $F"
	done
}

#
#  Recursively copy files defined in a shell variable to a target directory
#  in the staging tree.
#	
#
copy_files()
{
	VAR=$1;		shift	
	DIR=$1;		shift
	PERMD=$1;	shift
	PERMF=$1;	shift

	#
	#  Echo the value of the variable whose name is $VAR.
	#
	CMD='FILEs=$(echo $'$VAR')'
	eval $CMD

	if [ ! "$FILEs" ];  then
		echo "-$DIR"
		return
	fi
	#
	#  Make the staging directory.
	#
	mkdir -p $TMP/$DIR || die "$VAR: mkdir $TMP/$DIR failed"
	#
	#  Copy the files and directories into the staging directory
	#
	for F in $FILEs;  do
 		#
		#  The config file has a directory entry,
		#  so just make the directory.
		#
		if [ -d $F ];  then
			echo ">$DIR/$F/"
			DN=$TMP/$DIR/$F
			mkdir -p $DN || die "mkdir -p $DN failed"
			continue
		fi

		#
		#  The file lives in an uncreated directory.
		#
		DN=$(dirname $F | sed "s/^$DIR\///" | sed "s/^$DIR$//")
		if [ "$DN" -a ! -d $TMP/$DIR/$DN ];  then
			echo ">$DIR/$DN/"
			D="$TMP/$DIR/$DN"
			mkdir -p $D || die "mkdir -p $D failed"
		fi
		#
		#  Derive the target directory path.
		#
		#  Eliminate the /./ directory path component
		#  for clarity.
		#
		case "$DN" in
		''|.)
			D=$DIR
			;;
		*)
			D="$DIR/$DN"
		esac
		#
		#  Ought to check fo existence of file before copy?
		#
		echo ">$D/$(basename $F)"
		cp $F $TMP/$D || die "cp $F $TMP/$D failed"
	done
	find $TMP/$DIR -type d -print | xargs chmod $PERMD
	if [ "$FILEs" ];  then
		find $TMP/$DIR -type f -print | xargs chmod $PERMF
	fi
}

test $# = 0 && die "wrong number of arguments"

#
#  Read the configuration file.
#
case "$1" in
'')
	die "wrong number of argument"
	;;
--help)
	help
	exit 0
	;;
--template)
	cat <<END
#
#  Synopsis:
#	Configuration file read by make-dist to build tar files.
#  See Also:
#	https://github.com/jmscott/work/blob/master/make-dist
#
LIBs="
"

BINs="
"

SBINs="
"

CGIBINs="
"

HTDOCs="
"

SRCs="
"

ETC="
"

SPOOL="
"

RUN="
"

LOG="
"

END
	exit 0
	;;
-*)
	die "unknown option: $1"
	;;
*)
	CONF="$1"
	test -r "$CONF" || die "can't read configuration file: $CONF"
	;;
esac

#
#  Source in the configuration file.
#
. ./$CONF

#
#  PRODUCT is basename of directory, by default;
#  otherwise, whatever is set in the configuration file.
#
PRODUCT=${PRODUCT:=$(basename $(pwd))}

echo "# product is $PRODUCT"

#
#  Verify that files are readable.
#
is_readable BINs
is_readable SBINs
is_readable CGIBINs
is_readable LIBs
is_readable HTDOCs

#
#  Make temporary work directory.
#
TMP=tmp/$PROG.$$
test -d $TMP && die "tmp directory $TMP already exists"
mkdir -p $TMP || die "mkdir -p $TMP failed"
echo ">$TMP"

#
#  Copy files in various staging directories
#
#	copy_files VAR dir dir_perms file_perms
#
#  Does the order of the directories matter?
#  Probably ought to be the order defined in the file.
#
copy_files BASEs . u=rwx,g=rx,o= ug=rx,o=
#
#  Shouldn't bin/ be readable by world?
#
copy_files BINs bin u=rwx,g=rx,o= ug=rx,o=
copy_files SBINs sbin u=rwx,go= u=rx,go=
copy_files CGIBINs cgi-bin u=rwx,g=rx,o= ug=rx,o=
copy_files LIBs lib u=rwx,g=rx,o= ug=r,o=
copy_files SRCs src u=rwx,g=rx,o= ug=r,o=
copy_files HTDOCs htdocs u=wrx,g=rx,o= ug=r,o=

#
#  Tar up files into $PRODUCT-YYYYMMDD_HHmm.tar.bz2
#
TAR_FILE=$PRODUCT-$(date +'%Y%m%d_%H%M').tar.bz2
echo ">$TAR_FILE"
(
	cd $TMP || die "cd $TMP failed"
	#
	#  Tar up files in scratch directory.
	#  Need to check tar error status with ${PIPSTATUS[]}.
	#
	tar cf - $(ls | egrep '^(bin|sbin|cgi-bin|lib|src|htdocs)$')
) | bzip2 --best >$TAR_FILE
test -s $TAR_FILE || die "empty tar file $TAR_FILE"

#
#  Zap the temporary scratch dir.
#
find $TMP -print | xargs chmod +x
rm -rf $TMP || die "rm -rf $TMP failed"
exit 0
