#!/usr/bin/env perl
#
#  Synopsis:
#	Set the title bar of an xterm.
#  Usage:
#	xtitle groucho
#  Note:
#	Need to rename to set-xterm-title, since script with same name exists.
#
use strict;

print("\e]0;@ARGV\7");
