#!/usr/bin/perl -w
#
#  Synopsis:
#	Set the title bar of an xterm.
#  Usage:
#	xtitle groucho
#  Blame:
#	John the Scott, jmscott@setspace.com
#  Subversion Id:
#	$Id: xtitle 9 2010-06-27 10:11:04Z jmscott $
#
use strict;

print("\e]0;@ARGV\7");
