#!/usr/bin/perl
#
#  Synopsis:
#	Parse standard input as XML::Parse tree and Data::Dumper to stdout
#  Usage:
#	xml-parse-dump <file.xml
#  Depends:
#	Perl modules XML::Parser and Data::Dumper
#
use XML::Parser;
use Data::Dumper;

if (@ARGV != 0) {
	die "unknown argument: $ARGV[0]" if $ARGV[0] ne '--help';
	print <<END;
usage: xml-dump [--help] <file.xml
END
	exit;
}

my $parser = XML::Parser->new(
		Style => 'Tree'
	) or die "XML::Parser->new(Tree) failed: $!";
print Dumper($parser->parse(*STDIN));
