#!/usr/bin/env bash
#
#  Synopsis:
#	Build a tar or populate makefile from a shell sourcable config file.
#  Usage:
#	make-dist help
#	make-dist template >foobar.dist
#	make-dist tar foobar.dist
#  See:
#	https://github.com/jmscott/work/blob/master/make-dist
#	https://en.wikipedia.org/wiki/Unix_filesystem
#  Note:
#	Add startup test for GNU sed!
#
#	- VAR->dir remaps only for a single directory.  for example,
#
#		LIBs->lib/schema
#	- The tar version insures that dynamic directories in foobar.conf
#	exist but does NOT ever overwrite, lest precious data be lost.
#	However, the Makefile version, does not insure, so make recipes
#	must be hand coded.  Adding an option to generate the install
#	recipes would be nice:
#
#		make-dist dynamic-dirs
#
#	Which could be manually spliced back into the Makefile.
#
#	- Add command "env" or "fs" to document environment variables in config
#	file that describe directories.
#	
#	Think deepky about recursive version that can combine *.dist files
#
#	Why are the dirs/ for copy_file() hardwired for BINs, SBINs, etc?
#	Should not thast list be derived from the dist file?
#
#	Add "unpack" action, which properly removes and unpacks *.tar.bz2
#	directories.  Will need to make no assumptions about the root directory
#	files.  In other words, if, say, dir sbin/ is not in the tar file,
#	then "unpack" would NOT remove an existing /sbin/ on the target.
#	This algorithm implies knowing the difference between static dirs
#	like /sbin/, /lib/, etc versus dynatic dirs like /run/, /spool/.
#	Perhaps if the directory is empty in the tar file, then we can
#	safely assume the directory is dynamic and NOT to be removed on the
#	target.
#

die()
{
	echo "make-dist: ERROR: $@" >&2
	exit 1
}

[ "${BASH_VERSINFO:-0}" -ge 4 ] 					||
	die "bash version must be >= 4: ver ${BASH_VERSINFO:-0}" 

test $# = 0 && die "wrong number of arguments"

ACTION="$1";  shift
case "$ACTION" in
help)
	test $# = 0							||
		die "help: wrong number of arguments: got $#, expected 0"
	exec $JMSCOTT_ROOT/libexec/make-dist-help
	;;

template)
	test $# = 0							||
		die "template: wrong number of arguments: got $#, expected 0"
	exec cat $JMSCOTT_ROOT/lib/make-dist-template.dist
	;;
tar)
	test $# = 1							||
		die "tar: wrong number of arguments: got $#, expected 1"
	exec $JMSCOTT_ROOT/libexec/make-dist-tar $@
	;;
tars)
	test $# -lt 3 && die 						\
		"tars: wrong number of arguments: got $#, expected at least 2"
	exec $JMSCOTT_ROOT/libexec/make-dist-tars $@
	;;
*.dist)
	test $# = 0							||
		die "compat: wrong number of arguments: got $#, expected 0"
	exec $JMSCOTT_ROOT/libexec/make-dist-compat $ACTION
	;;
*)
	test -e "$ACTION" && die "dist file does not end in .dist: $ACTION"
	die "unknown action: $ACTION"
	;;
esac
