#!/usr/bin/env bash
#
#  Synopsis:
#	Libexeced by make-make to assemble a tar file for a single directory.
#  Usage:
#	make-make tar <path/to.mkmk>
#  See:
#	https://github.com/jmscott/work/blob/master/make-make
#	https://en.wikipedia.org/wiki/Unix_filesystem
#  Requires:
#	gnu sed
#	jmscott elapsed-english
#	gnu date
#  Note:
#	Make *_local versions of ALL variables that can be remapped in *.mkmk
#	file.  Currently only VAR2dir_local() can be remapped.  Need to also
#	remap dir2perm{} and file2perm{}.
#
#	Need option to keep temp work directory!
#
#	- VAR->dir remaps only for a single directory.  for example,
#
#		LIBs->lib/schema
#
#	- The tar version insures that dynamic directories in foobar.conf
#	exist but does NOT ever overwrite, lest precious data be lost.
#	However, the Makefile version, does not insure, so make recipes
#	must be hand coded.  Adding an option to generate the install
#	recipes would be nice:
#
#		make-make dirs-recipe
#
#	Which could be manually spliced back into the Makefile.
#	
#	Why are the dirs/ for copy_file() hardwired for BINs, SBINs, etc?
#	Should not that list be derived from the mkmk file?
#
#	Add "unpack" action, which properly removes and unpacks *.tar.bz2
#	directories.  Will need to make no assumptions about the root directory
#	files.  In other words, if, say, dir sbin/ is not in the tar file,
#	then "unpack" would NOT remove an existing /sbin/ on the target.
#	This algorithm implies knowing the difference between static dirs
#	like /sbin/, /lib/, etc versus dynatic dirs like /run/, /spool/.
#	Perhaps if the directory is empty in the tar file, then we can
#	safely assume the directory is dynamic and NOT to be removed on the
#	target.
#

PROG='make-make-tar'
START_EPOCH=$(date +%s)
MKMK=
WORK_TMP=

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

WARN()
{
	echo "$PROG: WARN: $@" >&2
}

leave()
{
	if [ -n "$WORK_TMP" -a -e $WORK_TMP ];  then
		echo "--$WORK_TMP"
		chmod -R +w $WORK_TMP					||
			WARN "chmod +w tmp/work failed: exit status=$?"
		find $WORK_TMP ! -type l -print | xargs chmod +w
		rm -rf $WORK_TMP || WARN "rm work tmp failed: exit status=$?"
	fi
	cat <<END
#
#  Date: $(date)
#
#  $PROG: good bye, cruel world: $(elapsed-english $START_EPOCH) elapsed
#
END
}

trap leave EXIT QUIT TERM
MKMK=$1;  shift

echo
cat <<END
#
#  $PROG:  hello, world
#  which make-make: $(which make-make)
#
#  JMSCOTT_ROOT=$JMSCOTT_ROOT
#  PATH=$PATH
#
#  bash version: $(bash --version | head -1)
#  Date: $(date)
#
END

#  map directory name to create permisions.

declare -A dir2perm=(
	[archive]='u=wrx,go='
	[attic]='u=wrx,go='
	[bin]='u=rwx,g=rx,o='
	[cache]='u=wrx,go='
	[cgi-bin]='u=rwx,g=rx,o='
	[data]='u=wrx,go='
	[dist]='u=wrx,go='
	[etc]='u=wrx,g=rx,o='
	[htdocs]='u=wrx,g=rx,o='
	[include]='u=rwx,go=rx'
	[lib]='u=rwx,go=rx'
	[libexec]='u=rwx,go=rx'
	[log]='u=wrx,g=rx,o='
	[run]='u=wrx,go='
	[sbin]='u=rwx,go='
	[spool]='u=wrx,go='
	[src]='u=rwx,g=rx,o='
	[tmp]='ug=wrx,o='
)

#  map directory name to copy file permisions.

declare -A file2perm=(
	[bin]='ug=rx,o='
	[cgi-bin]='ug=rx,o='
	[htdocs]='ug=r,o='
	[include]='ugo=r'
	[lib]='ugo=r'
	[libexec]='ugo=rx'
	[sbin]='u=rx,go='
	[src]='ugo=r'
)

#  map VAR name to directory name

declare -A VAR2dir=(
	[ARCHIVE]='archive'
	[ATTIC]='attic'
	[BINs]='bin'
	[CACHE]='cache'
	[CGIBINs]='cgi-bin'
	[DATA]='data'
	[DIST]='dist'
	[ETC]='etc'
	[HTDOCSs]='htdocs'
	[INCLUDEs]='include'
	[LIBEXECs]='libexec'
	[LIBs]='lib'
	[LOG]='log'
	[RUN]='run'
	[SBINs]='sbin'
	[SPOOL]='spool'
	[SRCs]='src'
	[TMP]='tmp'
)

#  user dist file can override the mapping from a vars, like LIBs,
#  to the default directory.

declare -A VAR2dir_local

is_readable()
{
	VAR=$1
	CMD='FILES=$(echo $'$VAR')'
	eval $CMD
	for F in $FILES;  do
		test -r $F || die "$VAR: can't read file $F"
	done
}

make_SYMLINKs()
{
	test -n "$SYMLINKs" || return
	for S in $SYMLINKs;  do
		echo $S | fgrep -e '->' | sed 's/->/ /' | while read A B;  do
		echo "+$A -> $B" && (
			cd $WORK_TMP || die "cd symlink failed: exit status=$?"
			BD=$(dirname $B)
			if [ ! -d $BD ];  then
				echo "+>$BD"
				#  no permisions!!!
				mkdir -p $BD				||
					die 'make_SYMLINKs: mkdir failed: '\
					     "exit status=$?"
			fi
			ln -sf $B $A || die "ln -fs failed: exit status=$?"
		)
		done
	done
}

#
#  Recursively copy files defined in a shell variable to a target directory
#  in the staging tree.
#
copy_file()
{
	VAR=$1;		shift
	DIR="${VAR2dir[$VAR]}"
	PERMD="${dir2perm[$DIR]}"
	PERMF="${file2perm[$DIR]}"

	#
	#  Echo the value of the variable whose name is $VAR.
	#
	CMD='FILEs=$(echo $'$VAR')'
	eval $CMD

	if [ ! "$FILEs" ];  then
		echo "-$DIR"
		return
	fi
	#
	#  Make the staging directory.
	#
	echo "+>$DIR"
	mkdir -p $WORK_TMP/$DIR						||
		die "copy_file: mkdir stage root failed: exit status=$?"
	#
	#  Copy the files and directories into the staging directory
	#
	for F in $FILEs;  do
 		#
		#  The config file has a directory entry,
		#  so just make the directory.
		#
		if [ -d $F ];  then
			echo "+>$DIR/$F/"
			DN=$WORK_TMP/$DIR/$F
			mkdir -p "$DN"					||
				die "copy_file: mkdir config failed: "	\
					"exit status=$?"
			continue
		fi

		#
		#  The file lives in an uncreated directory.
		#
		DN=$(dirname $F | sed "s:^$DIR\/::" | sed "s:^$DIR$::")
		if [ -n "$DN" -a ! -d $WORK_TMP/$DIR/$DN ];  then
			echo "+>$DIR/$DN/"
			D=$WORK_TMP/$DIR/$DN
			mkdir -p $D					||
				die "copy_file: mkdir failed: exit status=$?"
		fi
		#
		#  Derive the target directory path.
		#
		#  Eliminate the /./ directory path component
		#  for clarity.
		#
		case "$DN" in
		''|.)
			D=$DIR
			;;
		*)
			D="$DIR/$DN"
		esac
		#
		#  Ought to check fo existence of file before copy?
		#
		echo ">$D/$(basename $F)"
		cp $F $WORK_TMP/$D					||
			die "copy_file: cp failed: exit status=$?"
	done

	#  set the permissions in the work temp directory

	find $WORK_TMP/$DIR -type d -print | xargs chmod $PERMD
	STATUS=${PIPESTATUS[*]}
	test "$STATUS" = '0 0'						||
		die "copy_file: find work dir | chmod failed:"		\
			"exit status=$STATUS"

	if [ "$FILEs" ];  then
		find $WORK_TMP/$DIR -type f -print | xargs chmod $PERMF
		STATUS=${PIPESTATUS[*]}
		test "$STATUS" = '0 0'					||
			die "find copy work | chmod failed: exit status=$STATUS"
	fi
}

#  Makefile an empty directory
make_dir()
{
	VAR=$1

	DIR="${VAR2dir[$VAR]}"
	EXISTS=$(eval "echo \${$VAR+$VAR}")
	case "$EXISTS" in
	$VAR)
		echo "+$DIR"
		;;
	'')
		echo "-$DIR"
		return
		;;
	*)
		die "make_dir: unexpected eval: $EXISTS"
		;;
	esac

	PERMD="${dir2perm[$DIR]}"
	test -n "$PERMD" || die "make_dir: no perms: $DIR"

	#
	#  Make the staging directory.
	#
	echo "+>$WORK_TMP/$DIR"
	mkdir -p $WORK_TMP/$DIR						||
		die "make_dir: mkdir failed: exit status=$?"
	find $WORK_TMP/$DIR -type d -print | xargs chmod $PERMD
	STATUS=${PIPESTATUS[*]}
	test "$STATUS" = '0 0' ||
		die "make_dir: find dir | chmod failed: status=$STATUS"
}

test -r "$MKMK" || die "can't read make-make file: $MKMK"

#
#  Source in the configuration file.
#
. ./$MKMK

#  remap local VAR declarations to new directory paths

for V in "${!VAR2dir_local[@]}"; do
	ORIG_D="${VAR2dir[$V]}"
	test -n "$ORIG_D" || die "can not map original var to directory: $V"

	PERMD="${dir2perm[$ORIG_D]}"
	test -n "$PERMD" || die "no perms for original dir: $ORIG_D"
	PERMF="${file2perm[$ORIG_D]}"
	test -n "$PERMF" || die "no perms for original dir/file: $ORIG_D"

	NEW_D="${VAR2dir_local[$V]}"
	VAR2dir[$V]="$NEW_D"
	dir2perm[$NEW_D]="$PERMD"
	file2perm[$NEW_D]="$PERMF"
	echo "+$V->${VAR2dir[$V]} ($PERMD) ($PERMF)"

done

#
#  TAR_FILE is basename of directory, by default;
#  otherwise, whatever is set in the configuration file.
#
TAR_FILE=$(basename $MKMK .mkmk)

echo "#  tar file base name is $TAR_FILE"

#
#  Verify that files are readable.
#
is_readable BINs
is_readable CGIBINs
is_readable HTDOCSs
is_readable INCLUDEs
is_readable LIBEXECs
is_readable LIBs
is_readable SBINs

#
#  Make temporary work directory.
#
TMPDIR=${TMPDIR:=/tmp}
WORK_TMP=$TMPDIR/$PROG.$$.d
test -d $WORK_TMP && die "tmp directory $WORK_TMP already exists"
echo "+>$WORK_TMP"
mkdir -p $WORK_TMP || die "mkdir -p $WORK_TMP failed"

#  make directories, if variables defined in mkmk file

make_dir ARCHIVE
make_dir ATTIC
make_dir BINs
make_dir CACHE
make_dir CGIBINs
make_dir DATA
make_dir DIST
make_dir ETC
make_dir HTDOCSs
make_dir INCLUDEs
make_dir LIBEXECs
make_dir LIBs
make_dir LOG
make_dir RUN
make_dir SBINs
make_dir SPOOL
make_dir SRCs
make_dir SYNC
make_dir TMP
make_dir WWW

#
#  Copy files in various staging directories
#
#	copy_file VAR dir dir_perms file_perms
#
#  Does the order of the directories matter?
#  Probably ought to be the order defined in the file.
#
copy_file BINs
copy_file CGIBINs
copy_file HTDOCSs
copy_file INCLUDEs
copy_file LIBEXECs
copy_file LIBs
copy_file SBINs
copy_file SRCs

make_SYMLINKs 

#
#  Tar up files into $TAR_FILE-YYYYMMDD_hhmm.tar.bz2
#
TAR_FILE=$TAR_FILE-$(date +'%Y%m%d_%H%M').tar.bz2
echo ">>$TAR_FILE"
(
	cd $WORK_TMP || die "cd $WORK_TMP failed"
	#
	#  Tar up files in scratch directory.
	#  Need to check tar error status with ${PIPSTATUS[]}.
	#
	tar cf - . || die "tar cf failed: exit status=$?"
) | bzip2 --best >$TAR_FILE
STATUS=${PIPESTATUS[*]}
test "$STATUS" = '0 0'							||
	die "tar | bzip2 failed: exist status=$STATUS"

test -s $TAR_FILE || die "empty tar file $TAR_FILE"

exit 0
